import Home from "./Home";
import AboutUs from "./AboutUs";
import Contact from "./Contact";
import Blog from "./Blog";
import Courses from "./Courses";
import Login from "./Login";
import Apply from "./Apply";
import Certificate from "./Certificate";
import Services from "./Services";
import Internship from "./Internship";
import WebDevelopment from "./WebDevelopment";
import DigitalMarketing from "./DigitalMarketing";
import GraphicDesigning from "./GraphicDesigning";
import VideoEditing from "./VideoEditting";
import SocialMediaGainer from "./SocialMediaGainer";
import Dashboard from "./Dashboard";
export { Home, AboutUs, Contact, Blog, Courses, Login, Apply, Certificate, WebDevelopment, DigitalMarketing, GraphicDesigning, VideoEditing, SocialMediaGainer, Services, Internship, Dashboard };
